import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: "Minh Quang",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: "Versache1",
      slug: "versache-1",
      category: "Men",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "D&B",
      rating: 4.5,
      numReviews: 10,
      description: "high quality perfume",
    },
    {
      //_id: '2',
      name: "Versache2",
      slug: "versache-2",
      category: "Men",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "D&B",
      rating: 3.5,
      numReviews: 10,
      description: "high quality perfume",
    },
    {
      //_id: '3',
      name: "Versache3",
      slug: "versache-3",
      category: "Men",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "D&B",
      rating: 4.5,
      numReviews: 10,
      description: "high quality perfume",
    },
    {
      //_id: '4',
      name: "Versache4",
      slug: "versache-4",
      category: "Men",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "D&B",
      rating: 4.5,
      numReviews: 10,
      description: "high quality perfume",
    },
  ],
};
export default data;
